spring:
  application:
    name: limits-service
  jackson:
    time-zone: UTC
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.time_zone: UTC
  liquibase:
    change-log: classpath:db/changelog-master.yaml

api:
  prefix: /api/v1

limits:
  default:
    daily: 10000.00
  window:
    anchorZone: Europe/Moscow
  autoCreateClient: true
